### ISSUE TITLE
code off backend

### ISSUE THREAD

**Issue by ajatsoft** [geesoon/JomFit_App_Frontend#1]
can you share code off backend?
thankyou

**Comment by geesoon** [comment]
Hey there, @ajatsoft . I have just uploaded the backend code in another repository. Here's the [code](https://github.com/geesoon/JomFit_App_Backend) 

Just a disclaimer here. I only did the front end part (Flutter). The back end of JomFit is done by my friend Jones Yap. Also there are dependencies that are outdated, please use the latest version.
